In [35]:
import numpy as np

raw_data_np=np.genfromtxt('Loan-data.csv',delimiter=';',encoding='latin1',skip_header=1)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [37]:
raw_data_np[0]

array([48010226.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       13.33,
           1184.86,         nan,         nan,         nan,         nan,         nan,     9452.96])

In [39]:
np.set_printoptions(suppress=True,linewidth=100,precision=2)  # set the default parameters in numpy 'set_printoptions'

In [41]:
np.isnan(raw_data_np).sum()

88005

In [ ]:
min_value=np.nanmin(raw_data_np,axis=0)
max_value=np.nanmax(raw_data_np,axis=0)

In [77]:
print(max_value)

[68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97
         nan         nan         nan         nan         nan    41913.62]


In [ ]:
temporary_mean=np.nanmean(raw_data_np,axis=0)

In [103]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [105]:
min_value

array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
             nan,       nan,       nan,       nan,       nan,      0.  ])

In [107]:
np.isnan(temporary_mean)

array([False,  True, False,  True, False,  True, False, False,  True,  True,  True,  True,  True,
       False])

In [125]:
column_strings=np.argwhere(np.isnan(temporary_mean)).squeeze()  # squeeze fuction flattens the 2d array to 1d 

In [123]:
column_numeric=np.argwhere(np.isnan(temporary_mean)==False).squeeze()

In [137]:
load_data_strings=np.genfromtxt('Loan-data.csv',delimiter=';',encoding='latin1',skip_header=1,autostrip=True,usecols=column_strings,dtype=str)
load_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [139]:
load_data_numeric=np.genfromtxt('Loan-data.csv',delimiter=';',encoding='latin1',skip_header=1,autostrip=True,usecols=column_numeric,dtype=str)
load_data_numeric

array([['48010226', '35000.0', '35000.0', '13.33', '1184.86', '9452.96'],
       ['57693261', '30000.0', '30000.0', 'þëè.89', '938.57', '4679.7'],
       ['59432726', '15000.0', '15000.0', 'íîå.53', '494.86', '1969.83'],
       ...,
       ['50415990', '10000.0', '10000.0', 'þëè.89', '', '2185.64'],
       ['46154151', '', '10000.0', '16.55', '354.3', '3199.4'],
       ['66055249', '10000.0', '10000.0', 'þëè.26', '309.97', '301.9']], dtype='<U11')

In [159]:
header_full=np.genfromtxt('Loan-data.csv',delimiter=';',encoding='latin1',autostrip=True,skip_footer=raw_data_np.shape[0],dtype=str)

In [161]:
header_full[column_strings] # filters the strings headers 

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [163]:
header_full[column_numeric] # filters the numeric headers 

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [171]:
load_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [173]:
np.unique(load_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')